server:
  port: 8080

spring:
  application:
    name: spring-boot-rest-api
  
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${OIDC_INTROSPECTION_URI:https://oauth2.googleapis.com/tokeninfo}
          client-id: ${OIDC_CLIENT_ID:}
          client-secret: ${OIDC_CLIENT_SECRET:}

# Application specific configuration
app:
  jwt:
    secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast256BitsLongForHmacSha256AlgorithmSecurity}
    expiration: 1200 # 20 minutes in seconds
    max-session-duration: 86400 # 24 hours in seconds
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging configuration
logging:
  level:
    com.example.springbootrestapi: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"