server:
  port: 8080

spring:
  application:
    name: spring-boot-rest-api
  
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: ${OIDC_INTROSPECTION_URI:https://oauth2.googleapis.com/tokeninfo}
          client-id: ${OIDC_CLIENT_ID:}
          client-secret: ${OIDC_CLIENT_SECRET:}

# Application specific configuration
app:
  jwt:
    secret: ${JWT_SECRET:myVeryLongSecretKeyThatIsAtLeast256BitsLongForHmacSha256AlgorithmSecurity}
    expiration: 1200 # 20 minutes in seconds
    max-session-duration: 86400 # 24 hours in seconds
  cors:
    allowed-origins: ${FRONTEND_URL:http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# Actuator configuration for health checks and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
    info:
      enabled: true
    metrics:
      enabled: true
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Logging configuration
logging:
  level:
    com.example.springbootrestapi: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.actuator: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/spring-boot-rest-api.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# Application info for actuator
info:
  app:
    name: Spring Boot REST API
    description: A secure REST API with OIDC authentication and JWT session management
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 17